import type {
  AnalysisResponse,
  AnalysisStatusResponse,
  ChatMessage,
  ForensicReport,
  ReportListItem,
  SystemStatus,
  VideoListItem,
  YouTubeAuthResponse,
  ScriptRewriteRequest,
  ScriptRewriteResponse,
} from "@/types/database";

const rawApiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
export const API_BASE = rawApiUrl.endsWith("/api/v1")
  ? rawApiUrl
  : `${rawApiUrl.replace(/\/$/, "")}/api/v1`;

/**
 * Builds the YouTube OAuth initiation URL pointing to the active backend.
 */
export function getYouTubeAuthUrl(userId?: string): string {
  return `${API_BASE}/auth/youtube${userId ? `?user_id=${encodeURIComponent(userId)}` : ""}`;
}

/**
 * Builds request headers with Supabase JWT bearer or Guest Evaluator header.
 */
async function getAuthHeaders(): Promise<HeadersInit> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };

  try {
    if (typeof window !== "undefined") {
      const { createClient } = await import("@/lib/supabase/client");
      const supabase = createClient();
      
      // Guard against indefinite lock contention with a 1200ms timeout
      const sessionPromise = supabase.auth.getSession();
      const timeoutPromise = new Promise<{ data: { session: null } }>((resolve) =>
        setTimeout(() => resolve({ data: { session: null } }), 1200)
      );

      const {
        data: { session },
      } = await Promise.race([sessionPromise, timeoutPromise]);

      if (session?.access_token) {
        headers["Authorization"] = `Bearer ${session.access_token}`;
        return headers;
      }
    }
  } catch (err) {
    console.warn("Could not retrieve Supabase session:", err);
  }

  // Fallback to guest evaluator mode
  headers["X-Guest-Session"] = "true";
  headers["Authorization"] = "Bearer guest-evaluator-token";

  if (typeof document !== "undefined" && document.cookie.includes("cutpoint_guest_channel_disconnected=true")) {
    headers["X-Guest-Channel-Disconnected"] = "true";
  }

  return headers;
}


/**
 * Initiates the 8-agent retention forensic analysis pipeline.
 */
export async function startAnalysis(videoId: string): Promise<AnalysisResponse> {
  const headers = await getAuthHeaders();
  const res = await fetch(`${API_BASE}/analyze`, {
    method: "POST",
    headers,
    body: JSON.stringify({ video_id: videoId.trim() }),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Failed to queue analysis (${res.status}): ${errorText}`);
  }

  return res.json();
}

/**
 * Polls real-time step progress of an ongoing analysis run.
 */
export async function getAnalysisStatus(
  analysisId: string
): Promise<AnalysisStatusResponse> {
  const headers = await getAuthHeaders();
  const res = await fetch(`${API_BASE}/analyses/${analysisId}/status`, {
    method: "GET",
    headers,
    cache: "no-store",
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Status check failed (${res.status}): ${errorText}`);
  }

  return res.json();
}

/**
 * Lists all completed analysis reports for the authenticated user.
 */
export async function getReports(): Promise<ReportListItem[]> {
  const headers = await getAuthHeaders();
  const res = await fetch(`${API_BASE}/reports`, {
    method: "GET",
    headers,
    cache: "no-store",
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Failed to fetch reports (${res.status}): ${errorText}`);
  }

  return res.json();
}

/**
 * Permanently deletes a forensic retention report from the database.
 */
export async function deleteReport(
  analysisId: string
): Promise<{ success: boolean; message: string }> {
  const headers = await getAuthHeaders();
  const res = await fetch(`${API_BASE}/reports/${encodeURIComponent(analysisId)}`, {
    method: "DELETE",
    headers,
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Failed to delete report (${res.status}): ${errorText}`);
  }

  return res.json();
}

/**
 * Retrieves the full ForensicReport JSON payload.
 */
export async function getReport(analysisId: string): Promise<ForensicReport> {
  const headers = await getAuthHeaders();
  const res = await fetch(`${API_BASE}/reports/${analysisId}`, {
    method: "GET",
    headers,
    cache: "no-store",
  });

  if (res.status === 202) {
    throw new Error("Report is still being generated by the multi-agent pipeline.");
  }

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Failed to load report (${res.status}): ${errorText}`);
  }

  return res.json();
}

/**
 * Fetches recent uploads from the user's channel or pre-cached demo catalog.
 */
export async function getVideos(): Promise<VideoListItem[]> {
  const headers = await getAuthHeaders();
  const res = await fetch(`${API_BASE}/videos`, {
    method: "GET",
    headers,
    cache: "no-store",
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Failed to fetch videos (${res.status}): ${errorText}`);
  }

  return res.json();
}

/**
 * Generates the Google OAuth authorization URL for linking a YouTube channel.
 */
export async function connectYouTube(): Promise<YouTubeAuthResponse> {
  const headers = await getAuthHeaders();
  const res = await fetch(`${API_BASE}/auth/youtube`, {
    method: "POST",
    headers,
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`YouTube auth failed (${res.status}): ${errorText}`);
  }

  // Clear guest disconnected flag if present when connecting
  if (typeof document !== "undefined") {
    document.cookie = "cutpoint_guest_channel_disconnected=; path=/; max-age=0";
    window.dispatchEvent(new CustomEvent("cutpoint_channel_updated"));
  }

  return res.json();
}

/**
 * Disconnects the linked YouTube channel(s).
 */
export async function disconnectYouTube(channelId?: string): Promise<{ success: boolean; message: string }> {
  const headers = await getAuthHeaders();
  const url = channelId
    ? `${API_BASE}/auth/youtube?channel_id=${encodeURIComponent(channelId)}`
    : `${API_BASE}/auth/youtube`;

  const res = await fetch(url, {
    method: "DELETE",
    headers,
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Failed to disconnect YouTube channel (${res.status}): ${errorText}`);
  }

  // Set guest disconnected cookie flag so demo channels stay disconnected
  if (typeof document !== "undefined") {
    document.cookie = "cutpoint_guest_channel_disconnected=true; path=/; max-age=86400";
    window.dispatchEvent(new CustomEvent("cutpoint_channel_updated"));
  }

  return res.json();
}

/**
 * Restores the demo channel connection in guest evaluation mode.
 */
export function restoreGuestChannel(): void {
  if (typeof document !== "undefined") {
    document.cookie = "cutpoint_guest_channel_disconnected=; path=/; max-age=0";
    window.dispatchEvent(new CustomEvent("cutpoint_channel_updated"));
  }
}

/**
 * Checks system readiness and 8-agent roster status.
 */
export async function getSystemStatus(): Promise<SystemStatus> {
  const res = await fetch(`${API_BASE}/status`, {
    method: "GET",
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error(`Failed checking system status (${res.status})`);
  }

  return res.json();
}

/**
 * Streams interactive chat advice token-by-token using Server-Sent Events (SSE).
 */
export async function streamChat(
  analysisId: string,
  message: string,
  onToken: (token: string) => void,
  onError?: (err: Error) => void
): Promise<void> {
  const headers = await getAuthHeaders();

  const response = await fetch(`${API_BASE}/chat`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      analysis_id: analysisId,
      message,
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    const error = new Error(`Chat stream failed (${response.status}): ${errText}`);
    onError?.(error);
    throw error;
  }

  if (!response.body) {
    throw new Error("No readable stream received from chat endpoint");
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || !trimmed.startsWith("data:")) continue;

        const dataStr = trimmed.replace(/^data:\s*/, "");
        if (dataStr === "[DONE]") {
          return;
        }

        try {
          const parsed = JSON.parse(dataStr);
          if (parsed.error) {
            const err = new Error(parsed.error);
            onError?.(err);
            throw err;
          }
          if (parsed.token) {
            onToken(parsed.token);
          }
        } catch (e) {
          // If not valid JSON, check if token is raw
          if (e instanceof SyntaxError) {
            continue;
          }
          throw e;
        }
      }
    }
  } finally {
    reader.releaseLock();
  }
}

/**
 * Retrieves chat history for a specific report.
 */
export async function getChatHistory(analysisId: string): Promise<ChatMessage[]> {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3500);

    const headers = await getAuthHeaders();
    const res = await fetch(`${API_BASE}/chat/${analysisId}/history`, {
      method: "GET",
      headers,
      signal: controller.signal,
      cache: "no-store",
    });

    clearTimeout(timeoutId);

    if (!res.ok) {
      return [];
    }

    return await res.json();
  } catch (err) {
    console.warn("Could not retrieve chat history from API:", err);
    return [];
  }
}

/**
  * Generates an AI retention script rewrite (Hook, Cliff Part, or Whole Script)
  * and automatically syncs it with the Supabase database.
  */
export async function rewriteScript(
  analysisId: string,
  request: ScriptRewriteRequest
): Promise<ScriptRewriteResponse> {
  const headers = await getAuthHeaders();
  const res = await fetch(`${API_BASE}/reports/${analysisId}/rewrite`, {
    method: "POST",
    headers,
    body: JSON.stringify(request),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Script rewrite generation failed (${res.status}): ${errorText}`);
  }

  return res.json();
}

/**
  * Fetches formatted NLE timeline markers (DaVinci CSV, Premiere CSV, EDL, YouTube chapters).
  */
export async function exportTimelineMarkers(
  analysisId: string,
  format: string,
  fps: number = 30.0
): Promise<string> {
  const headers = await getAuthHeaders();
  const res = await fetch(
    `${API_BASE}/reports/${analysisId}/export/${format}?fps=${fps}`,
    {
      method: "GET",
      headers,
    }
  );

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Export failed (${res.status}): ${errorText}`);
  }

  return res.text();
}


